# Generated by Django 4.1.2 on 2023-11-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbir', '0002_imagesearch_up_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesearch',
            name='up_date',
        ),
    ]
