# Generated by Django 4.1.2 on 2023-11-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir', '0003_remove_imagesearch_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedataset',
            name='image',
            field=models.ImageField(null=True, upload_to='image_data'),
        ),
        migrations.AlterField(
            model_name='imagesearch',
            name='image',
            field=models.ImageField(null=True, upload_to='image_search'),
        ),
        migrations.AlterModelTable(
            name='imagedataset',
            table='image_data',
        ),
    ]
