# Generated by Django 4.1.2 on 2023-11-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir', '0004_alter_imagedataset_image_alter_imagesearch_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesearch',
            name='contrast',
        ),
        migrations.RemoveField(
            model_name='imagesearch',
            name='entropy',
        ),
        migrations.RemoveField(
            model_name='imagesearch',
            name='homo',
        ),
        migrations.RemoveField(
            model_name='imagesearch',
            name='hue',
        ),
        migrations.RemoveField(
            model_name='imagesearch',
            name='satur',
        ),
        migrations.RemoveField(
            model_name='imagesearch',
            name='value',
        ),
        migrations.AddField(
            model_name='imagedataset',
            name='correl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='imagedataset',
            name='dissim',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='imagedataset',
            name='energy',
            field=models.FloatField(default=0.0),
        ),
    ]
