# Generated by Django 4.1.2 on 2023-11-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbir', '0005_remove_imagesearch_contrast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedataset',
            name='contrast',
        ),
        migrations.RemoveField(
            model_name='imagedataset',
            name='correl',
        ),
        migrations.RemoveField(
            model_name='imagedataset',
            name='dissim',
        ),
        migrations.RemoveField(
            model_name='imagedataset',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='imagedataset',
            name='entropy',
        ),
        migrations.RemoveField(
            model_name='imagedataset',
            name='homo',
        ),
        migrations.RemoveField(
            model_name='imagedataset',
            name='hue',
        ),
        migrations.RemoveField(
            model_name='imagedataset',
            name='satur',
        ),
        migrations.RemoveField(
            model_name='imagedataset',
            name='value',
        ),
    ]
