# Generated by Django 4.1.2 on 2023-11-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='cbir/img')),
                ('contrast', models.FloatField(default=0.0)),
                ('homo', models.FloatField(default=0.0)),
                ('entropy', models.FloatField(default=0.0)),
                ('hue', models.FloatField(default=0.0)),
                ('satur', models.FloatField(default=0.0)),
                ('value', models.FloatField(default=0.0)),
                ('similarity', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'images_data',
            },
        ),
        migrations.CreateModel(
            name='ImageSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='cbir/img_search')),
                ('contrast', models.FloatField(default=0.0)),
                ('homo', models.FloatField(default=0.0)),
                ('entropy', models.FloatField(default=0.0)),
                ('hue', models.FloatField(default=0.0)),
                ('satur', models.FloatField(default=0.0)),
                ('value', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'image_search',
            },
        ),
    ]
